# Generated by Django 5.1.3 on 2025-08-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='fcm',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
