# Generated by Django 5.1.3 on 2025-07-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_transferrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresss'},
        ),
        migrations.AlterModelOptions(
            name='transferrequest',
            options={'verbose_name': 'TransferRequest', 'verbose_name_plural': 'TransferRequests'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
    ]
