# Generated by Django 5.1.3 on 2025-08-01 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('laundries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='laundry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='laundries.laundry'),
        ),
    ]
