# Generated by Django 5.1.3 on 2025-07-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laundryservice',
            options={'verbose_name': 'LaundryService', 'verbose_name_plural': 'LaundryServices'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'ServiceCategory', 'verbose_name_plural': 'ServiceCategorys'},
        ),
        migrations.AlterModelOptions(
            name='subservice',
            options={'verbose_name': 'SubService', 'verbose_name_plural': 'SubServices'},
        ),
    ]
