# Generated by Django 5.1.3 on 2025-03-15 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laundryservice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='laundryservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='laundryservice',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='laundryservice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='laundryservice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='laundryservice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='laundryservice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='laundryservice',
            name='urgent_price',
        ),
    ]
