# Generated by Django 5.1.3 on 2025-08-01 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0002_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='laundry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='laundries.laundry'),
        ),
        migrations.DeleteModel(
            name='LaundryService',
        ),
    ]
