from django.db.models.signals import post_save
from django.dispatch import receiver
from services.models import Service
from laundries.models import Laundry
# قائمة بالخدمات الثابتة
DEFAULT_SERVICES = [
    {
        "name": "شنطة ظهر",
        "price": 1.00,
        "urgent_price": 20.00,
        "duration": 1,
        "category_id": 19,
    },
    {
        "name": "شنطة يد",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 19,
    },
    {
        "name": "جزمه قماش",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 19,
    },
    {
        "name": "جزمة جلد",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 19,
    },
    {
        "name": "جزمة اطفال",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 19,
    },
    {
        "name": "جزمه رياضيه",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 19,
    },
    {
        "name": "بالمتجر",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 18,
    },
    {
        "name": "سجادة صلاة",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 17,
    },
    {
        "name": "مهد",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 17,
    },
    {
        "name": "منشفة كبيرة",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 17,
    },
    {
        "name": "منشفة وسط",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 17,
    },
    {
        "name": "منشفة صغيرة",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 17,
    },
    {
        "name": "شرشف نفرين",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 17,
    },
    {
        "name": "شرشف نفر",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 17,
    },
    {
        "name": "مفرش نفرين",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 17,
    },
    {
        "name": "مفرش نفر",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 17,
    },
    {
        "name": "بطانية نفرين",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 17,
    },
    {
        "name": "بطانية نفر",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 17,
    },
    {
        "name": "فستان",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "بدلة باكستاني",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "كمام",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "طرحة",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "نقاب",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "عبايه",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "سكارف",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "ستاره",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "مريول",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "قميص عسكري",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "لاب كوت",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "بدلة طبيه",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "بشت",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "بدلة عسكريه",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "بجامه",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "قميص نسائي",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "شورت",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "جنز",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "بنطلون",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "بدله",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "قميص",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "تيشيرت",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "بوكسر",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "فانيله داخليه",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "سروال طويل",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "فروه",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "شماخ",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "ثوب ملون",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "ثوب ابيض",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 16,
    },
    {
        "name": "فستان",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "بدلة باكستاني",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "طرحة",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "نقاب",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "عبايه",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "سكارف",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "بشت",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "ستاره",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "مريول",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "قميص عسكري",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "لاب كوت",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "بدلة طبيه",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "بدلة عسكريه",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "شرابات",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "بجامه",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "قميص نسائي",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "شورت",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "جنز",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "بنطلون",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "بدله",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "قميص",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "تيشيرت",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "بوكسير",
        "price": 1.00,
        "urgent_price": 1.00,
        "duration": 1,
        "category_id": 15,
    },
    {
        "name": "فانيله داخليه",
        "price": 3.00,
        "urgent_price": 3.00,
        "duration": 1,
        "category_id": 14,
    },
    {
        "name": "سروال طويل",
        "price": 3.00,
        "urgent_price": 3.00,
        "duration": 1,
        "category_id": 14,
    },
    {
        "name": "فانيله",
        "price": 3.00,
        "urgent_price": 3.00,
        "duration": 1,
        "category_id": 14,
    },
    {
        "name": "شماغ/غترة",
        "price": 4.00,
        "urgent_price": 4.00,
        "duration": 1,
        "category_id": 14,
    },
    {
        "name": "ثوب ملون",
        "price": 4.00,
        "urgent_price": 8.00,
        "duration": 1,
        "category_id": 14,
    },
    {
        "name": "ثوب ابيض",
        "price": 4.00,
        "urgent_price": 6.00,
        "duration": 30,
        "category_id": 14,
    },
]

@receiver(post_save, sender=Laundry)
def create_services(sender, instance, created, **kwargs):
    if created:
        for service in DEFAULT_SERVICES:
            Service.objects.create(laundry=instance, **service)