# Generated by Django 5.1.3 on 2025-08-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laundries_count', models.PositiveIntegerField(default=0)),
                ('agents_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_jsut', models.DateField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('receipt_voucher', 'سند قبض'), ('payment_voucher', 'سند صرف'), ('deposit', 'إيداع'), ('withdraw', 'سحب'), ('bill_payment', 'دفع فواتير'), ('refund', 'استرداد')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('malaq_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
