# Generated by Django 5.1.3 on 2025-07-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('receipt_voucher', 'سند قبض'), ('payment_voucher', 'سند صرف'), ('deposit', 'إيداع'), ('withdraw', 'سحب'), ('bill_payment', 'دفع فواتير'), ('refund', 'استرداد')], max_length=50),
        ),
    ]
