# Generated by Django 5.1.3 on 2025-07-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='السؤال')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('category', models.CharField(max_length=50, verbose_name='التصنيف')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سؤال شائع',
                'verbose_name_plural': 'الأسئلة الشائعة',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'رسالة من المستخدم'), ('support', 'رسالة من الدعم الفني'), ('system', 'رسالة نظام')], max_length=10, verbose_name='نوع الرسالة')),
                ('content', models.TextField(verbose_name='محتوى الرسالة')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/', verbose_name='مرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
            ],
            options={
                'verbose_name': 'رسالة دعم فني',
                'verbose_name_plural': 'رسائل الدعم الفني',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التذكرة')),
                ('category', models.CharField(choices=[('general', 'استفسار عام'), ('technical', 'مشكلة تقنية'), ('billing', 'مشكلة فواتير'), ('order', 'مشكلة طلب'), ('complaint', 'شكوى'), ('suggestion', 'اقتراح')], default='general', max_length=20, verbose_name='التصنيف')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المعالجة'), ('resolved', 'محلول'), ('closed', 'مغلق')], default='open', max_length=15, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
            ],
            options={
                'verbose_name': 'تذكرة دعم فني',
                'verbose_name_plural': 'تذاكر الدعم الفني',
                'ordering': ['-created_at'],
            },
        ),
    ]
