# Generated by Django 5.1.3 on 2024-11-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
