# Generated by Django 5.1.3 on 2025-07-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_appsettings_appversion_otpapi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appversion',
            old_name='notes',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='appversion',
            old_name='version_number',
            new_name='version',
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='release_date',
        ),
        migrations.AddField(
            model_name='appversion',
            name='force_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appversion',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
