# Generated by Django 5.1.3 on 2024-12-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_slideshowimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='price_per_kg_delivery',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
