# Generated by Django 5.1.3 on 2025-07-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_notes_appversion_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='type_app',
            field=models.CharField(choices=[('hangeragent', 'وكيل معلاق'), ('hangermain', 'ملاق الرئيسي')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
