# Generated by Django 5.1.3 on 2025-07-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_appversion_type_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettings',
            options={'verbose_name': 'AppSettings', 'verbose_name_plural': 'AppSettings'},
        ),
        migrations.AlterModelOptions(
            name='appversion',
            options={'verbose_name': 'AppVersion', 'verbose_name_plural': 'AppVersions'},
        ),
        migrations.AlterModelOptions(
            name='otpapi',
            options={'verbose_name': 'OTPAPI', 'verbose_name_plural': 'OTPAPIs'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='slideshowimage',
            options={'ordering': ['order'], 'verbose_name': 'SlideShowImage', 'verbose_name_plural': 'SlideShowImages'},
        ),
    ]
