# Generated by Django 5.1.3 on 2025-08-01 22:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laundries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='تقييم من 1 إلى 5 نجوم', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='تعليق اختياري', null=True)),
                ('service_quality', models.IntegerField(default=5, help_text='تقييم جودة الخدمة', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('delivery_speed', models.IntegerField(default=5, help_text='تقييم سرعة التوصيل', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('price_value', models.IntegerField(default=5, help_text='تقييم مناسبة السعر', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='laundries.laundry')),
            ],
            options={
                'verbose_name': 'LaundryReview',
                'verbose_name_plural': 'LaundryReviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
