# Generated by Django 5.1.3 on 2025-07-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laundryreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'LaundryReview', 'verbose_name_plural': 'LaundryReviews'},
        ),
    ]
