# Generated by Django 5.1.3 on 2025-08-22 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0002_initial'),
        ('orders', '0003_alter_order_status'),
        ('reviews', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laundryreview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='laundryreview',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='laundry_reviews', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='laundryreview',
            unique_together={('laundry', 'user', 'order')},
        ),
    ]
