# Generated by Django 5.1.3 on 2025-07-19 18:00

import agent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('id_image', models.FileField(upload_to='id_images/', validators=[agent.models.validate_file_size])),
                ('license_number', models.CharField(max_length=20)),
                ('license_image', models.FileField(upload_to='license_images/', validators=[agent.models.validate_file_size])),
                ('city', models.CharField(choices=[('riyadh', 'الرياض'), ('dammam', 'الدمام'), ('jeddah', 'جدة'), ('khobar', 'الخبر'), ('mecca', 'مكة المكرمة'), ('medina', 'المدينة المنورة')], max_length=20)),
                ('vehicle_type', models.CharField(choices=[('car', 'سيارة'), ('motorcycle', 'دراجة نارية'), ('bicycle', 'دراجة هوائية')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
