# Generated by Django 5.1.3 on 2025-02-26 21:36

import agent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesagent',
            name='id_image',
            field=models.FileField(upload_to='id_images/', validators=[agent.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='salesagent',
            name='license_image',
            field=models.FileField(upload_to='license_images/', validators=[agent.models.validate_file_size]),
        ),
    ]
