# Generated by Django 5.1.3 on 2025-07-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesagent',
            options={'verbose_name': 'SalesAgent', 'verbose_name_plural': 'SalesAgents'},
        ),
    ]
