# Generated by Django 5.1.3 on 2025-08-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('x_map', models.CharField(max_length=100)),
                ('y_map', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.FileField(blank=True, null=True, upload_to='laundry_images/')),
                ('membership_start_date', models.DateField(blank=True, null=True)),
                ('membership_end_date', models.DateField(blank=True, null=True)),
                ('sales_percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_image', models.FileField(blank=True, null=True, upload_to='laundry_licenses/', verbose_name='صورة الرخصة')),
                ('commercial_record_image', models.FileField(blank=True, null=True, upload_to='commercial_records/', verbose_name='صورة السجل التجاري')),
            ],
            options={
                'verbose_name': 'Laundry',
                'verbose_name_plural': 'Laundrys',
            },
        ),
        migrations.CreateModel(
            name='LaundryHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('saturday', 'السبت'), ('sunday', 'الأحد'), ('monday', 'الاثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة')], max_length=10)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'LaundryHours',
                'verbose_name_plural': 'LaundryHours',
            },
        ),
        migrations.CreateModel(
            name='UserLaundryMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
