# Generated by Django 5.1.3 on 2025-02-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundry',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='laundry_images/'),
        ),
    ]
