# Generated by Django 5.1.3 on 2025-07-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundry',
            name='commercial_record_image',
            field=models.FileField(blank=True, null=True, upload_to='commercial_records/', verbose_name='صورة السجل التجاري'),
        ),
        migrations.AddField(
            model_name='laundry',
            name='license_image',
            field=models.FileField(blank=True, null=True, upload_to='laundry_licenses/', verbose_name='صورة الرخصة'),
        ),
    ]
