# Generated by Django 5.1.3 on 2025-07-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundries', '0003_laundry_commercial_record_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laundry',
            options={'verbose_name': 'Laundry', 'verbose_name_plural': 'Laundrys'},
        ),
        migrations.AlterModelOptions(
            name='laundryhours',
            options={'verbose_name': 'LaundryHours', 'verbose_name_plural': 'LaundryHours'},
        ),
    ]
