# Generated by Django 5.1.3 on 2025-08-01 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laundries', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'LaundryOrder',
                'verbose_name_plural': 'LaundryOrders',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('courier_accepted', 'التسليم للمندوب'), ('courier_on_the_way', 'المندوب في الطريق'), ('picked_up_from_customer', 'تم اخذها من العميل'), ('delivered_to_laundry', 'تم التسليم للمغسلة'), ('in_progress', 'الطلب قيد المعالجة'), ('ready_for_delivery', 'جاهز للتسليم'), ('delivery_by_courier', 'التوصيل عن طريق المندوب'), ('courier_accepted_delivery', 'المندوب قبل طلب التوصيل'), ('delivered_to_customer', 'تم تسليم الطلب للعميل'), ('delivered_to_courier', 'تم تسليم الطلب للمندوب'), ('completed', 'مكتمل'), ('canceled', 'تم الإلغاء')], max_length=30)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('delivery_method', models.CharField(blank=True, max_length=50, null=True)),
                ('delegate_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('normal', 'عادي'), ('urgent', 'مستعجل')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrderItem',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('successful', 'ناجح'), ('failed', 'فاشل'), ('pending', 'قيد الانتظار')], default='pending', max_length=10)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'PaymentDetail',
                'verbose_name_plural': 'PaymentDetails',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('COD', 'الدفع عند الاستلام'), ('CARD', 'الدفع باستخدام البطاقة'), ('STC', 'الدفع باستخدام STC')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'PaymentMethod',
                'verbose_name_plural': 'PaymentMethods',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(blank=True, max_length=20, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_expiry_date', models.CharField(blank=True, max_length=20, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'PaymentMethodsDetails',
                'verbose_name_plural': 'PaymentMethodsDetails',
            },
        ),
        migrations.CreateModel(
            name='SalesAgentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('delivery_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'SalesAgentOrder',
                'verbose_name_plural': 'SalesAgentOrders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('urgent_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_type', models.CharField(choices=[('normal', 'عادي'), ('urgent', 'مستعجل')], default='normal', max_length=10)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laundry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundries.laundry')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
            options={
                'verbose_name': 'Cart',
            },
        ),
    ]
