# Generated by Django 5.1.3 on 2025-07-19 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0002_initial'),
        ('laundries', '0002_initial'),
        ('orders', '0001_initial'),
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='laundry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundries.laundry'),
        ),
        migrations.AddField(
            model_name='order',
            name='laundry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundries.laundry'),
        ),
        migrations.AddField(
            model_name='order',
            name='sales_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agent.salesagent'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='laundryorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.paymentmethod'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.paymentmethod'),
        ),
        migrations.AddField(
            model_name='paymentmethodsdetails',
            name='payment_method',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.paymentmethod'),
        ),
        migrations.AddField(
            model_name='salesagentorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='salesagentorder',
            name='sales_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.salesagent'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'laundry', 'service')},
        ),
    ]
