# Generated by Django 5.1.3 on 2025-08-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('courier_accepted', 'التسليم للمندوب'), ('courier_on_the_way', 'المندوب في الطريق'), ('picked_up_from_customer', 'تم اخذها من العميل'), ('delivered_to_laundry', 'تم التسليم للمغسلة'), ('in_progress', 'الطلب قيد المعالجة'), ('ready_for_delivery', 'جاهز للتسليم'), ('delivery_by_courier', 'التوصيل عن طريق المندوب'), ('courier_accepted_delivery', 'المندوب قبل طلب التوصيل'), ('customer_accepted_end', 'استلم الطلب بنفسك'), ('delivered_to_customer', 'تم تسليم الطلب للعميل'), ('delivered_to_courier', 'تم تسليم الطلب للمندوب'), ('completed', 'مكتمل'), ('canceled', 'تم الإلغاء')], max_length=30),
        ),
    ]
