# Generated by Django 5.1.3 on 2025-07-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='laundryorder',
            options={'verbose_name': 'LaundryOrder', 'verbose_name_plural': 'LaundryOrders'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'OrderItem', 'verbose_name_plural': 'OrderItem'},
        ),
        migrations.AlterModelOptions(
            name='paymentdetail',
            options={'verbose_name': 'PaymentDetail', 'verbose_name_plural': 'PaymentDetails'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'PaymentMethod', 'verbose_name_plural': 'PaymentMethods'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethodsdetails',
            options={'verbose_name': 'PaymentMethodsDetails', 'verbose_name_plural': 'PaymentMethodsDetails'},
        ),
        migrations.AlterModelOptions(
            name='salesagentorder',
            options={'verbose_name': 'SalesAgentOrder', 'verbose_name_plural': 'SalesAgentOrders'},
        ),
    ]
