# Generated by Django 5.1.3 on 2025-03-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_sales_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('COD', 'الدفع عند الاستلام'), ('CARD', 'الدفع باستخدام البطاقة'), ('STC', 'الدفع باستخدام STC')], max_length=100),
        ),
    ]
